apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-devops-develop
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  destination:
    name: in-cluster
    namespace: test-devops-develop
  source:
    path: helm/test-devops
    repoURL: https://github.com/extosoft-devsecops/test-devops.git
    targetRevision: develop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
